language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
matrix:
  include:
    - python: "2.6"
      env: EXTRA_REQUIREMENTS="ordereddict==1.1"
    - python: "2.7"
      env: EXTRA_REQUIREMENTS=""
    - python: "3.2"
      env: EXTRA_REQUIREMENTS=""
    - python: "3.3"
      env: EXTRA_REQUIREMENTS=""
    - python: "3.4"
      env: EXTRA_REQUIREMENTS=""
install:
  - "pip install -r requirements.txt"
  - pip install -r $EXTRA_REQUIREMENTS
script:
  - nosetests
